stages:
  - restore
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"

# Restore NuGet packages
restore:
  stage: restore
  image: mcr.microsoft.com/dotnet/sdk:7.0 # Use the appropriate .NET SDK version
  script:
    - cd backend
    - dotnet restore
  artifacts:
    paths:
      - backend/.nuget/packages/
    expire_in: 1 week

# Build the project
build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0 # Use the appropriate .NET SDK version
  script:
    - cd backend
    - dotnet build --configuration Release
  artifacts:
    paths:
      - backend/bin/
      - backend/obj/
    expire_in: 1 week

# Run tests
test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0 # Use the appropriate .NET SDK version
  script:
    - cd backend
    - dotnet test --logger:trx
  artifacts:
    paths:
      - backend/TestResults/
    when: always