
   stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

build-backend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME ./backend
    - docker push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
  only:
    changes:
      - backend/**

build-frontend:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME ./frontend
    - docker push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
  only:
    changes:
      - frontend/**

build-database:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/database:$CI_COMMIT_REF_NAME ./database
    - docker push $CI_REGISTRY_IMAGE/database:$CI_COMMIT_REF_NAME
  only:
    changes:
      - database/**

test:
  stage: test
  script:
    - echo "Running tests..."
    - echo "Tests passed!"

deploy:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose.yml planit
  only:
    - main