stages:
  - pre-build
  - build
  - test
  - deploy
  - teardown

variables:
  DOCKER_TAG: $CI_COMMIT_REF_SLUG

# Pre-build stage
build-builder:
  stage: pre-build
  image: docker:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Preparing builder..."

# Build backend image
build-backend:
  stage: build
  image: docker:latest
  script:
    - docker build -f ./backend/dockerfile-backend -t registry.chasacademy.dev/chas-challenge-2025/group-13/plan-it/backend:${DOCKER_TAG} ./backend
    - docker push /plan-it/backend:${DOCKER_TAG}

# Build database image
build-database:
  stage: build
  image: docker:latest
  script:
    - docker build -f ./backend/dockerfile-sql -t registry.chasacademy.dev/chas-challenge-2025/group-13/plan-it/database:${DOCKER_TAG} ./database
    - docker push registry.chasacademy.dev/chas-challenge-2025/group-13/plan-it/database:${DOCKER_TAG}

# Build frontend image
build-frontend:
  stage: build
  image: docker:latest
  script:
    - docker build -f dockerfile-react -t registry.chasacademy.dev/chas-challenge-2025/group-13/plan-it/frontend:${DOCKER_TAG} ./frontend
    - docker push registry.chasacademy.dev/chas-challenge-2025/group-13/plan-it/frontend:${DOCKER_TAG}

# Deploy stage
deploy:
  stage: deploy
  image: docker:latest
  script:
    - docker stack deploy --compose-file docker-compose.yml plan-it
  environment:
    name: production/$CI_COMMIT_REF_NAME
    url: https://g13-$CI_COMMIT_REF_SLUG.cc25.chasacademy.dev
  only:
    - main

# Teardown stage
teardown:
  stage: teardown
  image: docker:latest
  script:
    - docker stack rm plan-it
  when: manual