version: '3.8'

services:
  backend:
    image: registry.example.com/plan-it/backend:${DOCKER_TAG}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__DefaultConnection: Server=database;Database=TeamAppDB;User=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
    networks:
      - app-network

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - app-network

  frontend:
    image: registry.example.com/plan-it/frontend:${DOCKER_TAG}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
    ports:
      - "3000:80"
    environment:
      API_URL: http://backend:5000
    networks:
      - app-network
    depends_on:
      - backend

  adminer:
    image: adminer:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: overlay