services:
  planit-frontend:
    image: registry.chasacademy.dev/chas-challenge-2025/group-13/planit/react:${DOCKER_TAG}
    networks:
      - planit-network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${STACK_NAME}-http.rule=Host(`${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.${STACK_NAME}-http.entrypoints=http
        - traefik.http.routers.${STACK_NAME}-http.middlewares=https-redirect
        - traefik.http.routers.${STACK_NAME}-https.rule=Host(`${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.${STACK_NAME}-https.entrypoints=https
        - traefik.http.routers.${STACK_NAME}-https.tls=true
        - traefik.http.routers.${STACK_NAME}-https.tls.certresolver=le
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].main=cc25.chasacademy.dev
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].sans=*.cc25.chasacademy.dev
        - traefik.http.services.${STACK_NAME}.loadbalancer.server.port=80
    environment:
      - API_URL=http://planit-backend:80

  planit-backend:
    image: registry.chasacademy.dev/chas-challenge-2025/group-12/planit/dotnet:${DOCKER_TAG}
    networks:
      - planit-network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.api-${STACK_NAME}-http.rule=Host(`api.${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.api-${STACK_NAME}-http.entrypoints=http
        - traefik.http.routers.api-${STACK_NAME}-http.middlewares=https-redirect
        - traefik.http.routers.api-${STACK_NAME}-https.rule=Host(`api.${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.api-${STACK_NAME}-https.entrypoints=https
        - traefik.http.routers.api-${STACK_NAME}-https.tls=true
        - traefik.http.routers.api-${STACK_NAME}-https.tls.certresolver=le
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].main=cc25.chasacademy.dev
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].sans=*.cc25.chasacademy.dev
        - traefik.http.services.api-${STACK_NAME}.loadbalancer.server.port=80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=planit-db;Database=planit;User=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
    depends_on:
      - planit-db

  adminer:
    image: adminer:latest
    networks:
      - planit-network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.db-${STACK_NAME}-http.rule=Host(`db.${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.db-${STACK_NAME}-http.entrypoints=http
        - traefik.http.routers.db-${STACK_NAME}-http.middlewares=https-redirect
        - traefik.http.routers.db-${STACK_NAME}-https.rule=Host(`db.${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.db-${STACK_NAME}-https.entrypoints=https
        - traefik.http.routers.db-${STACK_NAME}-https.tls=true
        - traefik.http.routers.db-${STACK_NAME}-https.tls.certresolver=le
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].main=cc25.chasacademy.dev
        - traefik.http.routers.<DIN-HTTPS-ROUTER>.tls.domains[0].sans=*.cc25.chasacademy.dev
        - traefik.http.services.db-${STACK_NAME}.loadbalancer.server.port=8080
    environment:
      - ADMINER_DEFAULT_SERVER=planit-db
    depends_on:
      - planit-db

  planit-db:
    image: registry.chasacademy.dev/chas-challenge-2025/group-12/planit/mssql-db:latest
    networks:
      - planit-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.storage == true
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=YES
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true

volumes:
  mssql-data:
    name: mssql-data-volume

networks:
  traefik-public:
    external: true
  planit-network:
    internal: true
