FROM node:23-alpine AS builder
WORKDIR /app
# Copy package.json for dependencies and install
COPY package.json package-lock.json .
RUN npm ci
COPY . .
RUN npm run build -- --config vite.config.docker.js

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
