version: "3.9"

services:
  planit-backend:
    image: registry.chasacademy.dev/chas-challenge-2025/group-13/plan-it/dotnet:${DOCKER_TAG}
    networks:
      - planit-network
      - traefik-public
    depends_on:
      - planit-db
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.api-${STACK_NAME}-http.rule=Host(`${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.api-${STACK_NAME}-http.entrypoints=http
        - traefik.http.routers.api-${STACK_NAME}-http.middlewares=https-redirect
        - traefik.http.routers.api-${STACK_NAME}-https.rule=Host(`${STACK_NAME}.cc25.chasacademy.dev`)
        - traefik.http.routers.api-${STACK_NAME}-https.entrypoints=https
        - traefik.http.routers.api-${STACK_NAME}-https.tls=true
        - traefik.http.routers.api-${STACK_NAME}-https.tls.certresolver=le
        - traefik.http.routers.api-${STACK_NAME}-https.tls.domains[0].main=cc25.chasacademy.dev
        - traefik.http.routers.api-${STACK_NAME}-https.tls.domains[0].sans=*.cc25.chasacademy.dev
        - traefik.http.services.api-${STACK_NAME}.loadbalancer.server.port=80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=planit-db;Database=PlanItDb;User Id=sa;Password=PlAn@iT!521;TrustServerCertificate=True

  planit-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PlAn@iT!521
    networks:
      - planit-network
    deploy:
      placement:
        constraints:
          - node.role == worker  # optional: restrict to workers

networks:
  planit-network:
  traefik-public:
    external: true
